### ISSUE TITLE
Werehog can erroneously climb up ledges into walls at HFR

### ISSUE THREAD

**Issue by hyperbx** [hedge-dev/UnleashedRecomp#324]

**Comment by s-ilent** [comment]
This bug causes the player to get stuck in Cool Edge inside a wall over a ledge, a few minutes into the stage. 
![Cool Edge Night](https://github.com/user-attachments/assets/0cfdbe87-3c3a-4e6f-8506-3be9247e111a)

**Comment by Hiderlink20** [comment]
I had a similar issue with this as well.  it happened in the cool edge stage but it also happened in dragon road.  Just after the part with the moon medal over floating boxes, I got myself stuck in a pole.  I could only leave by resetting the level or letting enemies kill me (my attacks can't hurt them while I'm stuck but they can hurt me).  I'll take note of the framerate issue in the future.

![Image](https://github.com/user-attachments/assets/dff6563e-41ab-40d6-bd51-afe91286251b)
![Image](https://github.com/user-attachments/assets/ad71c5f5-f5f0-4e67-8336-f38c7accb1c3)
![Image](https://github.com/user-attachments/assets/7660f425-8b60-4da3-ba1d-223c0aec7bee)

**Comment by Ztr00p3r** [comment]
First Level of Spagonia also has this. 

![Image](https://github.com/user-attachments/assets/fb5a45ef-3a3c-4497-86b1-964f9b6c06fd)

**Comment by SomeoneAtHome** [comment]
Also in Empire City Act 1
![Image](https://github.com/user-attachments/assets/976824d2-7e66-4c6b-bf93-5390422e0884)

**Comment by SebitaProgramador** [comment]
> Also in Empire City Act 1 ![Image](https://github.com/user-attachments/assets/976824d2-7e66-4c6b-bf93-5390422e0884)

![Image](https://github.com/user-attachments/assets/88521638-6ae6-433b-95d3-7ed1f73248b8)

**Comment by Caltery752** [comment]
this happented to me too

**Comment by hyperbx** [comment]
Fixed in #1570, should be in the next release.

https://github.com/user-attachments/assets/3fe4b56c-5a7a-4d35-9425-b53ef9c39270

<sub><sup>*Ignore the MGS sound effects.*</sup></sub>

**Comment by HammyBlamy1** [comment]
Welp here is 1 year later still the same problem....

<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/e6442dd3-d71b-439e-9917-bd2b6b89368d" />

**Comment by RagdollClash** [comment]
The issue has been fixed in the main branch, you can use the GitHub Actions build since they haven't expired yet. 

https://github.com/hedge-dev/UnleashedRecomp/actions/runs/28367503312

**Comment by HammyBlamy1** [comment]
> The issue has been fixed in the main branch, you can use the GitHub Actions build since they haven't expired yet.
> 
> https://github.com/hedge-dev/UnleashedRecomp/actions/runs/28367503312

Thanks!
