### ISSUE TITLE
Installer Music Credits?

### ISSUE THREAD

**Issue by Rings4** [hedge-dev/UnleashedRecomp#705]
Who is responsible for the wonderful music used in the installer? I would love to tag the FLAC file with their artist name and the track name, assuming they've given it a title. I didn't see mention of this in the credits on the main page.

**Comment by blueskythlikesclouds** [comment]
It's an anonymous contribution.

**Comment by Rings4** [comment]
> It's an anonymous contribution.

Interesting. So, does it not exist anywhere else online? Was it specifically made for and released with this installer? If so, I'm really wondering what I'm going to do about the artist tag, because I 100% want to add this track to my library, and I don't have any tracks that lack artist tags. Guess I can just credit it to hedge-dev?

**Comment by hyperbx** [comment]
You can find the raw WAV file for the installer music [here](https://github.com/hedge-dev/UnleashedRecompResources/raw/refs/heads/main/music/raw/installer.wav).

Feel free to attribute it to hedge-dev.

**Comment by Rings4** [comment]
> You can find the raw WAV file for the installer music [here](https://github.com/hedge-dev/UnleashedRecompResources/raw/refs/heads/main/music/raw/installer.wav).
> 
> Feel free to attribute it to hedge-dev.

Much appreciated. I did already find that, was just at an impasse as to who to credit it to. I'll use hedge-dev, thanks! Do you have a more-or-less official title/album name it should have? Otherwise, I think I'll name it "Sonic Unleashed Recomp Installer" for both.

**Comment by hyperbx** [comment]
The soundtrack has no official name, feel free to name it yourself.

**Comment by WaldyTMS** [comment]
I'm so happy someone asked about this. Whomever composed this track, can you please have them read my heartfelt thanks:

Hearing this track as I entered into the installer genuinely almost brought me to tears. I've been begging for years for Unleashed to come to PC in a stable functional state, and seeing the announcement had me giddy all day. But when I started to hear this track upon opening it, I genuinely felt like I was in a dream. It was as if the game was telling me, "The wait is finally over. Now enjoy your adventure!" 😭 Whomever you are, thank you so much!! I will treasure this music track for years to come!! ❤️

**Comment by Rings4** [comment]
> I'm so happy someone asked about this. Whomever composed this track, can you please have them read my heartfelt thanks:
> 
> Hearing this track as I entered into the installer genuinely almost brought me to tears. I've been begging for years for Unleashed to come to PC in a stable functional state, and seeing the announcement had me giddy all day. But when I started to hear this track upon opening it, I genuinely felt like I was in a dream. It was as if the game was telling me, "The wait is finally over. Now enjoy your adventure!" 😭 Whomever you are, thank you so much!! I will treasure this music track for years to come!! ❤️

Who are you and how did you get inside my head? That was 100% exactly my thoughts haha.

**Comment by FoxyLoon** [comment]
This should be fixed at the top.

Or add something about “installer music” to the home page of this repository.

I came looking for this. More people will surely come too. The music is beautiful, congratulations to the artist!

**Comment by FoxyLoon** [comment]
@Rings4 @hyperbx @WaldyTMS @blueskythlikesclouds (I'm not sure who I should talk to)
This should be fixed at the top.

Or add something about “installer music” to the home page of this repository.

I came looking for this. More people will surely come too. The music is beautiful, congratulations to the artist!

**Comment by Rings4** [comment]
> [@Rings4](https://github.com/Rings4) [@hyperbx](https://github.com/hyperbx) [@WaldyTMS](https://github.com/WaldyTMS) [@blueskythlikesclouds](https://github.com/blueskythlikesclouds) [@DeaTh-G](https://github.com/DeaTh-G) (I'm not sure who I should talk to)
> 
> This should be fixed at the top.
> 
> Or add something about “installer music” to the home page of this repository.
> 
> I came looking for this. More people will surely come too. The music is beautiful, congratulations to the artist!

Yeah, I'm surprised it's still not in the credits.

Also, I have a theory on who the artist may be: the Hat In Time composer, Pascal Michael Stiefel. That's probably why he wanted to remain anonymous, as he's a professional composer. It sounds like his work to me. So that's my headcanon, but I still have it attributed to hedge-dev as I listed above.

**Comment by futsuu-san** [comment]
> The soundtrack has no official name, feel free to name it yourself.

I named that "Dreams of World Adventure". What d'ya think?
